import type { Format, FormatOptions } from './registry.js';
import type { KnowledgeUnit } from '../schema/index.js';
import { isEnforceable, compareSeverity } from '../severity.js';

/**
 * AI Rules Markdown format.
 * Compiles knowledge units into .ai-rules markdown for repository configuration.
 *
 * This format is designed for use with AI coding assistants that read
 * repository-level rule files (e.g., .cursor/rules, .ai-rules.md).
 */
export const aiRulesMdFormat: Format = {
  name: 'ai-rules-md',
  description: 'Compiles knowledge units into .ai-rules markdown format',
  extension: '.md',

  compile(units: KnowledgeUnit[], options: FormatOptions): string {
    const lines: string[] = [];
    const brandName = options.brand || 'Default';

    // Header comment
    lines.push('<!-- AI Rules generated by Madrigal -->');
    lines.push(`<!-- Brand: ${brandName} -->`);
    lines.push(`<!-- Generated: ${new Date().toISOString()} -->`);
    lines.push(`<!-- Do not edit - regenerate with Madrigal -->`);
    lines.push('');

    // Title
    lines.push('# Design Rules');
    lines.push('');
    lines.push('These rules are enforced when working with this codebase.');
    lines.push('');

    // Filter to enforceable rules only (error, warning)
    const enforceableUnits = units.filter((u) => isEnforceable(u.severity));

    // Sort by severity (errors first)
    enforceableUnits.sort((a, b) => compareSeverity(a.severity, b.severity));

    // Group by severity
    const errors = enforceableUnits.filter((u) => u.severity === 'error');
    const warnings = enforceableUnits.filter((u) => u.severity === 'warning');

    if (errors.length > 0) {
      lines.push('## MUST Follow (Errors)');
      lines.push('');
      lines.push('These rules MUST be followed. Violations will block CI.');
      lines.push('');

      for (const unit of errors) {
        lines.push(formatRule(unit));
        lines.push('');
      }
    }

    if (warnings.length > 0) {
      lines.push('## SHOULD Follow (Warnings)');
      lines.push('');
      lines.push('These rules SHOULD be followed when possible.');
      lines.push('');

      for (const unit of warnings) {
        lines.push(formatRule(unit));
        lines.push('');
      }
    }

    // Add context rules in a collapsed section
    const contextUnits = units.filter(
      (u) => u.severity === 'context' || u.severity === 'info'
    );
    if (contextUnits.length > 0) {
      lines.push('## Additional Context');
      lines.push('');
      lines.push('<details>');
      lines.push('<summary>Background information for AI assistants</summary>');
      lines.push('');

      for (const unit of contextUnits) {
        lines.push(formatRule(unit));
        lines.push('');
      }

      lines.push('</details>');
    }

    return lines.join('\n');
  },
};

/**
 * Format a single rule as markdown.
 */
function formatRule(unit: KnowledgeUnit): string {
  const lines: string[] = [];

  lines.push(`### ${unit.title}`);
  lines.push('');

  if (unit.tags.length > 0) {
    lines.push(`*Tags: ${unit.tags.join(', ')}*`);
    lines.push('');
  }

  lines.push(unit.body);

  return lines.join('\n');
}
