import { compareEnforcement } from '../enforcement.js';
import type { KnowledgeUnit } from '../schema/index.js';
import type { Format, FormatOptions } from './registry.js';

/**
 * SKILL.md format.
 * Compiles knowledge units into a markdown skill file for AI agents.
 *
 * Output structure:
 * - Title and metadata header
 * - Grouped by domain
 * - Rules sorted by enforcement (must first)
 * - Each rule as a markdown section with tags
 */
export const skillMdFormat: Format = {
  name: 'skill-md',
  description: 'Compiles knowledge units into SKILL.md format for AI agents',
  extension: '.md',

  compile(units: KnowledgeUnit[], options: FormatOptions): string {
    const lines: string[] = [];
    const brandName = options.brand || 'Global';

    // Header
    lines.push(`# ${brandName} Design Knowledge`);
    lines.push('');
    lines.push(`> Auto-generated by Madrigal. Do not edit directly.`);
    lines.push(`> Generated: ${new Date().toISOString()}`);
    lines.push('');

    // Group by domain
    const byDomain = new Map<string, KnowledgeUnit[]>();
    for (const unit of units) {
      const domain = unit.domain || 'other';
      const existing = byDomain.get(domain);
      if (existing) {
        existing.push(unit);
      } else {
        byDomain.set(domain, [unit]);
      }
    }

    // Sort domains alphabetically
    const sortedDomains = Array.from(byDomain.keys()).sort();

    for (const domain of sortedDomains) {
      const domainUnits = byDomain.get(domain) ?? [];

      // Sort units by enforcement (most strict first)
      domainUnits.sort((a, b) =>
        compareEnforcement(a.enforcement, b.enforcement),
      );

      lines.push(`## ${formatDomainTitle(domain)}`);
      lines.push('');

      for (const unit of domainUnits) {
        lines.push(formatUnit(unit));
        lines.push('');
      }
    }

    return lines.join('\n');
  },
};

/**
 * Format a domain name as a title.
 */
function formatDomainTitle(domain: string): string {
  return domain
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Format a knowledge unit as markdown.
 */
function formatUnit(unit: KnowledgeUnit): string {
  const lines: string[] = [];

  // Title with enforcement badge
  const enforcementBadge = getEnforcementBadge(unit.enforcement);
  lines.push(`### ${unit.title} ${enforcementBadge}`);
  lines.push('');

  // Tags if present
  if (unit.tags.length > 0) {
    lines.push(`Tags: ${unit.tags.map((t) => `\`${t}\``).join(', ')}`);
    lines.push('');
  }

  // Body content
  lines.push(unit.body);

  return lines.join('\n');
}

/**
 * Get an enforcement badge.
 */
function getEnforcementBadge(enforcement: string): string {
  switch (enforcement) {
    case 'must':
      return '[MUST]';
    case 'should':
      return '[SHOULD]';
    case 'may':
      return '[MAY]';
    case 'context':
      return '[CONTEXT]';
    case 'deprecated':
      return '[DEPRECATED]';
    default:
      return '';
  }
}
