/**
 * Origin of a knowledge unit.
 *
 * - human-authored: Created directly by a human expert
 * - system-proposed: Generated by an automated system, pending review
 * - extracted: Extracted from existing documentation or source material
 */
export type ProvenanceOrigin =
  | 'human-authored'
  | 'system-proposed'
  | 'extracted';

/**
 * Status of a proposal for system-proposed or extracted knowledge.
 */
export type ProposalStatus =
  | 'draft'
  | 'pending-review'
  | 'approved'
  | 'rejected';

/**
 * Provenance tracks the origin and approval status of knowledge units.
 */
export interface Provenance {
  /** How this knowledge unit was created */
  origin: ProvenanceOrigin;

  /** Confidence score from 0-1. Human-authored starts at 1.0 */
  confidence: number;

  /** User ID who approved this knowledge unit */
  approvedBy?: string;

  /** ISO 8601 timestamp of approval */
  approvedAt?: string;

  /** Links or references supporting this knowledge */
  evidence?: string[];

  /** Current status in the review workflow */
  proposalStatus?: ProposalStatus;
}

export function createHumanProvenance(approvedBy?: string): Provenance {
  const now = new Date().toISOString();
  return {
    origin: 'human-authored',
    confidence: 1.0,
    approvedBy,
    approvedAt: approvedBy ? now : undefined,
    proposalStatus: approvedBy ? 'approved' : undefined,
  };
}

export function createSystemProposedProvenance(
  confidence: number,
  evidence?: string[],
): Provenance {
  return {
    origin: 'system-proposed',
    confidence: Math.max(0, Math.min(1, confidence)),
    evidence,
    proposalStatus: 'draft',
  };
}

export function createExtractedProvenance(
  confidence: number,
  evidence: string[],
): Provenance {
  return {
    origin: 'extracted',
    confidence: Math.max(0, Math.min(1, confidence)),
    evidence,
    proposalStatus: 'pending-review',
  };
}

/**
 * Create provenance for a file-loaded knowledge unit.
 * Used by the loader when reading markdown files from disk.
 */
export function createFileProvenance(): Provenance {
  return { origin: 'human-authored', confidence: 1.0 };
}
